export type env = {
  Bindings: {
    MONGODB_URI: string;
    JWT_SECRET: string;
    EMAIL_QUEUE: string;
    API_KEY: string;
    ENVIRONMENT: string;
    R2_BUCKET: string;
    UPSTASH_REDIS_REST_URL: string;
    UPSTASH_REDIS_REST_TOKEN: string;
    R2_ACCESS_KEY: string;
    R2_SECRET_KEY: string;
    NODE_ENV: string;
    API_VERSION: string;
    MAX_ATTACHMENT_SIZE: string;
    ALLOWED_MIME_TYPES: string;
    EMAIL_RETENTION_DAYS: string;
    SEARCH_INDEX_BATCH_SIZE: string;
    REDIS_URL: string;
    REDIS_TOKEN: string;
    MAILCHANNELS_API_KEY: string;
    R2_ACCOUNT_ID: string;
    ALLOWED_ORIGINS: string;
    EMAIL_DOMAIN: string;
    DEFAULT_FROM_EMAIL: string;
    EMAIL_STORE: KVNamespace;
    SEARCH_INDEX: KVNamespace;
    CACHE_STORE: KVNamespace;
    KV_STORE: KVNamespace;
    ATTACHMENT_BUCKET: R2Bucket;
    BACKUP_BUCKET: R2Bucket;
    EMAIL_DB: D1Database;
    ANALYTICS_DB: D1Database;
  };
};
